# Mesh configuration
mesh:
  filename: "mesh/beam_732.msh"
  fem_degree: 1  # Degree of the finite element space

# Material properties
material:
  youngs_modulus: 10000
  poissons_ratio: 0.45
  density: 1000
  volume: 10.0

# Physics simulation parameters
physics:
  gravity: [0, -9.8, 0]  # Format as array for proper SOFA integration
  dt: 0.01
  rayleigh_stiffness: 0.1
  rayleigh_mass: 0.1
  solver_iterations: 1000
  solver_tolerance: 1e-10
  solver_threshold: 1e-10

# Constraint parameters
constraints:
  fixed_box: [-0.01, -0.01, -0.01, 0.01, 1.01, 1.01]  # [xmin, ymin, zmin, xmax, ymax, zmax]

# Neural model configuration
model:
  latent_dim: 10
  hid_layers: 32
  hid_dim: 32
  use_modal_derivatives: true

# Training parameters
training:
  num_epochs: 50
  learning_rate: 0.001
  checkpoint_dir: "checkpoints"
  tensorboard_dir: "tensorboard"
  skip_training: false
  lbfgs_start_epoch: 0  # Epoch to switch to LBFGS
  lbfgs_learning_rate: 1.0  # Learning rate for LBFGS

# Matrix handling configuration
matrices:
  use_sofa_matrices: true
  matrices_path: "matrices"
  timestamp: null  # Set to specific timestamp or null for latest